version: 2.1

orbs:
  terraform: 'circleci/terraform@2.1'

parameters:
  environment:
    type: string
    default: ""
jobs:
  sg:
    executor: terraform/default
    steps:
      - run:
          command: >-
                GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
                git clone https://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@github.com/Shantanusri123/security_group.git
          name: GIT Clone ec2-instance-tfvars repository
      - run:
          command: >-
                GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
                git clone https://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@github.com/Shantanusri123/security_group_tfvars.git
          name: GIT Clone ec2-instance repository
      - run:
          name: terraform init
          command: terraform -chdir="./security_group" init
      - run:
          name: "terraform create workspace"
          command: terraform workspace new <<pipeline.parameters.environment>>
      - terraform/validate:
          path: "./security_group"
      - run:
          name: "terraform plan"
          command: terraform -chdir="./security_group" plan -var-file="../security_group_tfvars/<<pipeline.parameters.environment>>.tfvars"
      - persist_to_workspace:
          root: .
          paths: .
    working_directory: ~src

  sg-apply:
    executor: terraform/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "terraform apply"
          command: terraform -chdir="./security_group" apply -auto-approve -var-file="../security_group_tfvars/<<pipeline.parameters.environment>>.tfvars"
      - run:
          command: cd ./securitygroup | ls
    working_directory: ~src

  ec2:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
                GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
                git clone https://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@github.com/Shantanusri123/ec2-instance-tfvars.git
          name: GIT Clone ec2-instance-tfvars repository
      - run:
          command: >-
                GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
                git clone https://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@github.com/Shantanusri123/ec2-Instance.git
          name: GIT Clone ec2-instance repository
      - run:
          name: terraform init
          command: terraform -chdir="./ec2-Instance" init
      - run:
          name: "terraform create workspace"
          command: terraform workspace new <<pipeline.parameters.environment>>
      - terraform/validate:
          path: "./ec2-Instance"
      - run:
          name: "terraform plan"
          command: terraform -chdir="./ec2-Instance" plan -var-file="../ec2-instance-tfvars/<<pipeline.parameters.environment>>.tfvars"
      - persist_to_workspace:
          root: .
          paths: .
    working_directory: ~src

  ec2-apply:
    executor: terraform/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "terraform apply"
          command: terraform -chdir="./ec2-Instance" apply -auto-approve -var-file="../ec2-instance-tfvars/<<pipeline.parameters.environment>>.tfvars"
    working_directory: ~src
workflows:
  CircleCI_Terraform_Pipeline: 
    jobs:
      - sg
      - hold:
          name: sg-apply-hold
          type: approval
          requires:
            - sg
      - sg-apply:
          requires:
            - sg-apply-hold
      - ec2:
          requires:
            - sg-apply
      - hold:
          name: ec2-apply-hold
          type: approval
          requires:
            - ec2
      - ec2-apply:
          requires:
            - ec2-apply-hold