version: 2.1

orbs:
  terraform: 'circleci/terraform@2.1'

parameters:
  environment:
    type: string
    default: ""
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
                GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
                git clone https://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@github.com/Shantanusri123/ec2-instance-tfvars.git
          name: GIT Clone ec2-instance-tfvars repository
      - run:
          command: >-
                GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
                git clone https://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@github.com/Shantanusri123/ec2-Instance.git
          name: GIT Clone ec2-instance repository
      - terraform/init:
          path: "./ec2-Instance"
      - run:
          name: "terraform create workspace"
          command: terraform workspace new <<pipeline.parameters.environment>>
      - terraform/validate:
          path: 
      - run:
          name: "terraform plan"
          command: terraform -chdir="./ec2-Instance" plan -var-file="../ec2-instance-tfvars/<<pipeline.parameters.environment>>.tfvars"
      - persist_to_workspace:
          root: .
          paths: .
    working_directory: ~src

  apply-job-lifecycle:
    executor: terraform/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "terraform apply"
          command: terraform apply -auto-approve -var-file "./ec2-instance-tfvars/<<pipeline.parameters.environment>>.tfvars"
    working_directory: ~src
workflows:
  single-job-lifecycle: 
    jobs:
      - single-job-lifecycle
      - hold:
          type: approval
          requires:
            - single-job-lifecycle
      - apply-job-lifecycle:
          requires:
            - hold
